[package]
name = "inidll2"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  

[dependencies]
configparser = "3.1.0"
ini = "1.3.0"
windows = { version = "0.54.0", features = [
    "Win32_Foundation", 
    "Win32_System_LibraryLoader"
]}
